#!/bin/sh -e

arg=$1
base=`basename $arg`
root_log="$base"_simulation.log
make $arg.bin_f
simulator/simulator $arg.bin > $root_log
echo "grep INST"
cat $root_log | grep "^INST" > "$base"_inst.log
echo "grep REG"
cat $root_log | grep "^REG" > "$base"_reg.log
echo "grep MEM"
cat $root_log | grep "^MEM" > "$base"_mem.log
echo "file copy"
cp $arg.bin ../mips/instruction.dat
size=`wc $arg.bin | awk '{ print $1 }'`
sed ../mips/instruction_memory.v -e "s/MEM_SIZE=.*;/MEM_SIZE=$size;/" > inst.v
mv inst.v ../mips/instruction_memory.v
